export const ADD_SHIPPING = 'ADD_SHIPPING_ADDRESS';
export const ADD_BILLING = 'ADD_BILLING_ADDRESS';
export const ADD_ORDER = 'ADD_ORDER_DETAILS';
export const ADD_PRODUCT_SPEC = 'ADD_PRODUCT_SPEC';
export const SHOW_DETAILS = 'SHOW_DETAILS';
export const SUBMIT_DETAILS = 'SUBMIT_DETAILS';